//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazilimYapimi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logSatis
    {
        public int SatisId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Urun { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> AliciId { get; set; }
        public Nullable<int> SaticiId { get; set; }
    }
}
