//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazilimYapimi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class obakiye
    {
        public int obakiyeid { get; set; }
        public int k_id { get; set; }
        public Nullable<int> bakiye { get; set; }
        public string cins { get; set; }
    }
}
