//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazilimYapimi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public int u_id { get; set; }
        public Nullable<int> k_id { get; set; }
        public Nullable<int> miktar { get; set; }
        public Nullable<int> fiyat { get; set; }
        public string urun { get; set; }
    
        public virtual kullanici kullanici { get; set; }
    }
}
